const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * EduChain Deployment Script
 * Deploys contracts and updates frontend config
 */
async function main() {
  console.log("🚀 Starting EduChain deployment to localhost...");

  const [deployer] = await hre.ethers.getSigners();
  console.log("👤 Deployer:", deployer.address);
  console.log(
    "💰 Balance:",
    hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)),
    "ETH"
  );

  const deployedContracts = {};
  const deploymentInfo = {
    network: hre.network.name,
    chainId: (await hre.ethers.provider.getNetwork()).chainId,
    deployer: deployer.address,
    deploymentTime: new Date().toISOString(),
    contracts: {},
  };

  try {
    // 1️⃣ Deploy EduChainNFT
    console.log("\n📋 Deploying EduChainNFT...");
  const EduChainNFT = await hre.ethers.getContractFactory("EduChainNFT");
    const eduChainNFT = await EduChainNFT.deploy();
    await eduChainNFT.waitForDeployment();
    const eduChainNFTAddress = await eduChainNFT.getAddress();

    deployedContracts.EduChainNFT = eduChainNFTAddress;
    deploymentInfo.contracts.EduChainNFT = {
      address: eduChainNFTAddress,
      name: await eduChainNFT.name(),
      symbol: await eduChainNFT.symbol(),
      owner: await eduChainNFT.owner(),
    };
    console.log("✅ EduChainNFT deployed:", eduChainNFTAddress);

    // 2️⃣ Deploy BookMarketplace
    console.log("\n📋 Deploying BookMarketplace...");
    const BookMarketplace = await hre.ethers.getContractFactory("BookMarketplace");
    const bookMarketplace = await BookMarketplace.deploy();
    await bookMarketplace.waitForDeployment();
    const bookMarketplaceAddress = await bookMarketplace.getAddress();

    deployedContracts.BookMarketplace = bookMarketplaceAddress;
    deploymentInfo.contracts.BookMarketplace = {
      address: bookMarketplaceAddress,
      owner: await bookMarketplace.owner(),
    };
    console.log("✅ BookMarketplace deployed:", bookMarketplaceAddress);

    // 3️⃣ Deploy Lock contract (for testing)
    console.log("\n📋 Deploying Lock contract...");
    const Lock = await hre.ethers.getContractFactory("Lock");
    const unlockTime = BigInt(Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60); // 1 year
    const lock = await Lock.deploy(unlockTime, { value: hre.ethers.parseEther("0.001") });
    await lock.waitForDeployment();
    const lockAddress = await lock.getAddress();

    deployedContracts.Lock = lockAddress;
    deploymentInfo.contracts.Lock = {
      address: lockAddress,
      unlockTime: unlockTime.toString(), // BigInt → string
      owner: await lock.owner(),
    };
    console.log("✅ Lock deployed:", lockAddress);

    // 4️⃣ Update frontend addresses config
    await updateAddressesConfig(deployedContracts);

    // 5️⃣ Save deployment info
    await saveDeploymentInfo(deploymentInfo);

    console.log("\n🎉 Deployment completed successfully!");
    console.log("📋 Contracts deployed:", deployedContracts);

  } catch (error) {
    console.error("❌ Deployment failed:", error);
    throw error;
  }
}

async function updateAddressesConfig(contracts) {
  const configPath = path.join(__dirname, "..", "client", "src", "config", "addresses.js");
  if (!fs.existsSync(path.dirname(configPath))) {
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
  }

  const content = `// Auto-generated by deploy.js
export const NFT_CONTRACT_ADDRESS = "${contracts.EduChainNFT}";
export const LOCK_CONTRACT_ADDRESS = "${contracts.Lock}";
export const CONTRACT_ADDRESSES = {
  EduChainNFT: "${contracts.EduChainNFT}",
  Lock: "${contracts.Lock}"
};
export const DEPLOYMENT_TIMESTAMP = "${new Date().toISOString()}";
`;
  fs.writeFileSync(configPath, content);
  console.log("✅ Frontend addresses config updated:", configPath);
}

async function saveDeploymentInfo(deploymentInfo) {
  const dir = path.join(__dirname, "..", "deployments", "localhost");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `deployment-${Date.now()}.json`);

  // BigInt-safe JSON stringify
  const jsonStringifySafe = (obj) =>
    JSON.stringify(obj, (key, value) => (typeof value === "bigint" ? value.toString() : value), 2);

  fs.writeFileSync(file, jsonStringifySafe(deploymentInfo));
  console.log("✅ Deployment info saved:", file);
}

// Run deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:", error);
    process.exit(1);
});
